name: CD Pipeline

on:
  push:
    branches:
      - main
  # TODO: Remove when finsished testing
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Pull Latest Docker Image
        run: docker pull ${{secrets.DOCKER_USERNAME}}/task-api:latest

      - name: Run Task-Api in Docker
        run: |
          docker run -d -p 3000:3000 --name task-api ${{secrets.DOCKER_USERNAME}}/task-api:latest
          sleep 10
          echo "Get all $(curl -s 'http://localhost:3000/api/tasks')"
          docker stop task-api
          docker rm task-api