name: Bump Version and Builder Docker Image

on:
  push:
    branches:
      - main
  
  # For testing. Remove later
  pull_request:
    branches:
      - main

jobs:
  version-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
      - name: Install dependencies
        run: npm ci

      - name: Bump Version
        run: |
          npm version minor -m "CI: bump version to %s"
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push new version commit and tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git push origin main --follow-tags
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-api:${NEW_VERSION} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/task-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:${NEW_VERSION}
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:latest
